// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schematas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AdminAuditLogList struct {
	_tab flatbuffers.Table
}

func GetRootAsAdminAuditLogList(buf []byte, offset flatbuffers.UOffsetT) *AdminAuditLogList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AdminAuditLogList{}
	x.Init(buf, n+offset)
	return x
}

func FinishAdminAuditLogListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAdminAuditLogList(buf []byte, offset flatbuffers.UOffsetT) *AdminAuditLogList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AdminAuditLogList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAdminAuditLogListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AdminAuditLogList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AdminAuditLogList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AdminAuditLogList) Logs(obj *AdminAuditLog, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AdminAuditLogList) LogsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AdminAuditLogListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AdminAuditLogListAddLogs(builder *flatbuffers.Builder, logs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(logs), 0)
}
func AdminAuditLogListStartLogsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AdminAuditLogListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
