// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schematas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AdminAuditLog struct {
	_tab flatbuffers.Table
}

func GetRootAsAdminAuditLog(buf []byte, offset flatbuffers.UOffsetT) *AdminAuditLog {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AdminAuditLog{}
	x.Init(buf, n+offset)
	return x
}

func FinishAdminAuditLogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAdminAuditLog(buf []byte, offset flatbuffers.UOffsetT) *AdminAuditLog {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AdminAuditLog{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAdminAuditLogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AdminAuditLog) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AdminAuditLog) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AdminAuditLog) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AdminAuditLog) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *AdminAuditLog) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AdminAuditLog) Action() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AdminAuditLog) Details() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AdminAuditLog) Ts() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AdminAuditLog) TsUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AdminAuditLog) MutateTsUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func AdminAuditLogStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func AdminAuditLogAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func AdminAuditLogAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(username), 0)
}
func AdminAuditLogAddAction(builder *flatbuffers.Builder, action flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(action), 0)
}
func AdminAuditLogAddDetails(builder *flatbuffers.Builder, details flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(details), 0)
}
func AdminAuditLogAddTs(builder *flatbuffers.Builder, ts flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(ts), 0)
}
func AdminAuditLogAddTsUnixMs(builder *flatbuffers.Builder, tsUnixMs int64) {
	builder.PrependInt64Slot(5, tsUnixMs, 0)
}
func AdminAuditLogEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
