// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schematas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DLQEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsDLQEntry(buf []byte, offset flatbuffers.UOffsetT) *DLQEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DLQEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishDLQEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDLQEntry(buf []byte, offset flatbuffers.UOffsetT) *DLQEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DLQEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDLQEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DLQEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DLQEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DLQEntry) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DLQEntry) PackageId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DLQEntry) Payload() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DLQEntry) ErrorCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DLQEntry) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DLQEntry) FailedAt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DLQEntry) FailedAtUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DLQEntry) MutateFailedAtUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *DLQEntry) Resolved() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DLQEntry) MutateResolved(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *DLQEntry) ResolvedAt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DLQEntry) ResolvedAtUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DLQEntry) MutateResolvedAtUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(22, n)
}

func DLQEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func DLQEntryAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func DLQEntryAddPackageId(builder *flatbuffers.Builder, packageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(packageId), 0)
}
func DLQEntryAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(payload), 0)
}
func DLQEntryAddErrorCode(builder *flatbuffers.Builder, errorCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(errorCode), 0)
}
func DLQEntryAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(errorMessage), 0)
}
func DLQEntryAddFailedAt(builder *flatbuffers.Builder, failedAt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(failedAt), 0)
}
func DLQEntryAddFailedAtUnixMs(builder *flatbuffers.Builder, failedAtUnixMs int64) {
	builder.PrependInt64Slot(6, failedAtUnixMs, 0)
}
func DLQEntryAddResolved(builder *flatbuffers.Builder, resolved bool) {
	builder.PrependBoolSlot(7, resolved, false)
}
func DLQEntryAddResolvedAt(builder *flatbuffers.Builder, resolvedAt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(resolvedAt), 0)
}
func DLQEntryAddResolvedAtUnixMs(builder *flatbuffers.Builder, resolvedAtUnixMs int64) {
	builder.PrependInt64Slot(9, resolvedAtUnixMs, 0)
}
func DLQEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
