// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schematas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JobAuditLogList struct {
	_tab flatbuffers.Table
}

func GetRootAsJobAuditLogList(buf []byte, offset flatbuffers.UOffsetT) *JobAuditLogList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JobAuditLogList{}
	x.Init(buf, n+offset)
	return x
}

func FinishJobAuditLogListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJobAuditLogList(buf []byte, offset flatbuffers.UOffsetT) *JobAuditLogList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JobAuditLogList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJobAuditLogListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JobAuditLogList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JobAuditLogList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JobAuditLogList) Logs(obj *JobAuditLog, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *JobAuditLogList) LogsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func JobAuditLogListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func JobAuditLogListAddLogs(builder *flatbuffers.Builder, logs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(logs), 0)
}
func JobAuditLogListStartLogsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func JobAuditLogListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
