// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schematas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JobAuditLog struct {
	_tab flatbuffers.Table
}

func GetRootAsJobAuditLog(buf []byte, offset flatbuffers.UOffsetT) *JobAuditLog {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JobAuditLog{}
	x.Init(buf, n+offset)
	return x
}

func FinishJobAuditLogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJobAuditLog(buf []byte, offset flatbuffers.UOffsetT) *JobAuditLog {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JobAuditLog{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJobAuditLogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JobAuditLog) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JobAuditLog) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JobAuditLog) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JobAuditLog) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *JobAuditLog) RunId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JobAuditLog) MutateRunId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *JobAuditLog) Component() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JobAuditLog) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JobAuditLog) Ts() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JobAuditLog) TsUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *JobAuditLog) MutateTsUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func JobAuditLogStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func JobAuditLogAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func JobAuditLogAddRunId(builder *flatbuffers.Builder, runId int64) {
	builder.PrependInt64Slot(1, runId, 0)
}
func JobAuditLogAddComponent(builder *flatbuffers.Builder, component flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(component), 0)
}
func JobAuditLogAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(message), 0)
}
func JobAuditLogAddTs(builder *flatbuffers.Builder, ts flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(ts), 0)
}
func JobAuditLogAddTsUnixMs(builder *flatbuffers.Builder, tsUnixMs int64) {
	builder.PrependInt64Slot(5, tsUnixMs, 0)
}
func JobAuditLogEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
