// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schematas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SystemLog struct {
	_tab flatbuffers.Table
}

func GetRootAsSystemLog(buf []byte, offset flatbuffers.UOffsetT) *SystemLog {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SystemLog{}
	x.Init(buf, n+offset)
	return x
}

func FinishSystemLogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSystemLog(buf []byte, offset flatbuffers.UOffsetT) *SystemLog {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SystemLog{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSystemLogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SystemLog) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SystemLog) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SystemLog) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SystemLog) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *SystemLog) Level() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SystemLog) Component() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SystemLog) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SystemLog) Ts() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SystemLog) TsUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SystemLog) MutateTsUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func SystemLogStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func SystemLogAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func SystemLogAddLevel(builder *flatbuffers.Builder, level flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(level), 0)
}
func SystemLogAddComponent(builder *flatbuffers.Builder, component flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(component), 0)
}
func SystemLogAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(message), 0)
}
func SystemLogAddTs(builder *flatbuffers.Builder, ts flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(ts), 0)
}
func SystemLogAddTsUnixMs(builder *flatbuffers.Builder, tsUnixMs int64) {
	builder.PrependInt64Slot(5, tsUnixMs, 0)
}
func SystemLogEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
