// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schematas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransformationErrorList struct {
	_tab flatbuffers.Table
}

func GetRootAsTransformationErrorList(buf []byte, offset flatbuffers.UOffsetT) *TransformationErrorList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransformationErrorList{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransformationErrorListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransformationErrorList(buf []byte, offset flatbuffers.UOffsetT) *TransformationErrorList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransformationErrorList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransformationErrorListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransformationErrorList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransformationErrorList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransformationErrorList) Errors(obj *TransformationError, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TransformationErrorList) ErrorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TransformationErrorListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TransformationErrorListAddErrors(builder *flatbuffers.Builder, errors flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(errors), 0)
}
func TransformationErrorListStartErrorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TransformationErrorListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
