// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schematas

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransformationError struct {
	_tab flatbuffers.Table
}

func GetRootAsTransformationError(buf []byte, offset flatbuffers.UOffsetT) *TransformationError {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransformationError{}
	x.Init(buf, n+offset)
	return x
}

func FinishTransformationErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTransformationError(buf []byte, offset flatbuffers.UOffsetT) *TransformationError {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransformationError{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTransformationErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TransformationError) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransformationError) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransformationError) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransformationError) CorrelationId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransformationError) Topic() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransformationError) FailedField() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransformationError) RuleName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransformationError) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransformationError) CreatedAt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TransformationError) CreatedAtUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TransformationError) MutateCreatedAtUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func TransformationErrorStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func TransformationErrorAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func TransformationErrorAddCorrelationId(builder *flatbuffers.Builder, correlationId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(correlationId), 0)
}
func TransformationErrorAddTopic(builder *flatbuffers.Builder, topic flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(topic), 0)
}
func TransformationErrorAddFailedField(builder *flatbuffers.Builder, failedField flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(failedField), 0)
}
func TransformationErrorAddRuleName(builder *flatbuffers.Builder, ruleName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(ruleName), 0)
}
func TransformationErrorAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(errorMessage), 0)
}
func TransformationErrorAddCreatedAt(builder *flatbuffers.Builder, createdAt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(createdAt), 0)
}
func TransformationErrorAddCreatedAtUnixMs(builder *flatbuffers.Builder, createdAtUnixMs int64) {
	builder.PrependInt64Slot(7, createdAtUnixMs, 0)
}
func TransformationErrorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
